language: php

# php compatibility
php: ["7.2", "7.3", "7.4snapshot"]

env:
  global:
    - PHP_CS_FIXER_FUTURE_MODE=1
    - PHP_CS_FIXER_IGNORE_ENV=1

matrix:
  allow_failures:
    - php: "7.4snapshot"

cache:
  - directories:
    - $HOME/.composer

before_script:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer install --no-interaction --prefer-dist

script:
  - vendor/bin/phplint
  - vendor/bin/php-cs-fixer fix --verbose
  - vendor/bin/phpcbf --colors -sp src/ tests/
  - vendor/bin/phpunit --testdox --verbose tests/Unit/
  - vendor/bin/phpstan analyse --no-progress --verbose --level max src/ tests/

notifications:
  email: false
